
- name: Debian-Based | Add Docker GPG key
  apt_key:
    url: "{{docker_debian_key_url}}"
    state: present
    keyring: "{{docker_debian_keyring_dir}}"

- name:  Debian-Based | echo docker apt source release
  command: "{{ item }}"
  with_items:
  - "install -m 0755 -d /etc/apt/keyrings"
  - "chmod a+r {{docker_debian_keyring_dir}}"
  - "echo '{{docker_debian_repository}}' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"

- name: Debian-Based | Add Docker apt repository
  apt_repository:
    repo: "{{docker_debian_repository}}"
    state: present
    filename: /etc/apt/sources.list.d/docker.list
    update_cache: yes

#- name: Run apt upgrade
#  apt:
#    upgrade: "yes"
#    update_cache: yes
#    cache_valid_time: 432000

- name: Debian-Based | Install Docker packages
  apt:
    name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    state: present
    update_cache: yes

- name:  Debian-Based | Ensure docker-compose is installed and available
  get_url: 
    url : "{{docker_compose_installation_repo}}"
    dest: "{{docker_compose_installation_path}}"
    mode: 'u+x,g+x'

- name: Debian-Based | Docker Installation Status
  debug:
    var: result.stdout_lines
