---
- hosts: all
  gather_facts: true
  roles:
    - docker-install
    - prometheus-grafana-install
    - exporters-install
  environment:
   http_proxy: "{{ http_proxy_address }}"
   https_proxy: "{{ https_proxy_address }}"

